// GENERATED by scripts/build-manifest.ts — do not edit by hand.
// Regenerate with `deno task build` (Node: `npm run build`, Bun: `bun run bun:build`).

/** The package version, as published to JSR and npm. */
export const VERSION: string = "0.10.0"; // x-release-please-version

/** One distributable file and where to load it from. */
export type UiAsset = {
  /** File name under dist/. */
  readonly file: string;
  /** Pinned jsDelivr URL for this exact version. */
  readonly url: string;
  /** Subresource-integrity hash of the file (sha384). */
  readonly integrity: string;
};

/** Versioned CDN base for the compiled bundle (jsDelivr, from npm). */
export const CDN_BASE: string = "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.10.0/dist"; // x-release-please-version

export const UI_CSS: UiAsset = {
  file: "ui.css",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.10.0/dist/ui.css", // x-release-please-version
  integrity: "sha384-WRAR5aAL2p0TBHKy/TS8lQiBHIxjqwuUlrbH5hb5LB6vb7GPMtMx4MxMj/nUhSnw",
};

export const UI_JS: UiAsset = {
  file: "ui.js",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.10.0/dist/ui.js", // x-release-please-version
  integrity: "sha384-wsJAEtLV3OZ6srF4cmyG7wL9Qa2PwNR/WFeZg5z0w4LJJd9iI3P7+ypqbqKxesbu",
};

/** The icon set as an SVG sprite (`<use href="…/icons.svg#icon-<name>">`, same-origin only). */
export const UI_ICONS: UiAsset = {
  file: "icons.svg",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.10.0/dist/icons.svg", // x-release-please-version
  integrity: "sha384-/0LWUw/lJPowwP79px9CF07PpnpumSzbKGSoNPfPdhjvnKQifI79mpdoBnesDZHf",
};

/** Every distributable, in load order. */
export const UI_ASSETS: readonly UiAsset[] = [UI_CSS, UI_JS, UI_ICONS];
