// GENERATED by scripts/build-manifest.ts — do not edit by hand.
// Regenerate with `deno task build` (Node: `npm run build`, Bun: `bun run bun:build`).

/** The package version, as published to JSR and npm. */
export const VERSION: string = "0.7.0"; // x-release-please-version

/** One distributable file and where to load it from. */
export type UiAsset = {
  /** File name under dist/. */
  readonly file: string;
  /** Pinned jsDelivr URL for this exact version. */
  readonly url: string;
  /** Subresource-integrity hash of the file (sha384). */
  readonly integrity: string;
};

/** Versioned CDN base for the compiled bundle (jsDelivr, from npm). */
export const CDN_BASE: string = "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.7.0/dist"; // x-release-please-version

export const UI_CSS: UiAsset = {
  file: "ui.css",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.7.0/dist/ui.css", // x-release-please-version
  integrity: "sha384-vuLHB2gkLVr/x2NfFjFg3g5Gt83PWwIttfnkdo3U0aFS9Lcp3XS0OBLRe0nHM1hA",
};

export const UI_JS: UiAsset = {
  file: "ui.js",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.7.0/dist/ui.js", // x-release-please-version
  integrity: "sha384-SScF6MjFtTOaZGksiBOvIHSUGyxfN3ONuxChSiU1k4DqMf1mHuJLXiFZh9sKXbMR",
};

/** The icon set as an SVG sprite (`<use href="…/icons.svg#icon-<name>">`, same-origin only). */
export const UI_ICONS: UiAsset = {
  file: "icons.svg",
  url: "https://cdn.jsdelivr.net/npm/@tundralibs/ui@0.7.0/dist/icons.svg", // x-release-please-version
  integrity: "sha384-/0LWUw/lJPowwP79px9CF07PpnpumSzbKGSoNPfPdhjvnKQifI79mpdoBnesDZHf",
};

/** Every distributable, in load order. */
export const UI_ASSETS: readonly UiAsset[] = [UI_CSS, UI_JS, UI_ICONS];
