/**
 * Writes version.ts from deno.json's version and the built dist/ files:
 * the package version, the jsDelivr URLs for `dist/ui.css` / `dist/ui.js`
 * at exactly that version, and their SRI hashes (sha384 of the bytes on
 * disk). The core template reads it, so a rAPId app on `assets: "cdn"`
 * gets a pinned, integrity-checked stylesheet and script with no config.
 *
 * Runs after build:css, build:js and build:icons. The file is committed
 * and the CI "manifest drift" step fails when it no longer matches a
 * fresh build. The version lines carry `x-release-please-version`
 * markers, so the release PR bumps them along with deno.json and
 * package.json — the hashes never change with the version, only the URLs.
 */
import { readFile, readTextFile, writeTextFile } from "@tundralibs/compat/file";

const manifest = JSON.parse(await readTextFile("deno.json")) as { name: string; version: string };
const npmName = manifest.name; // JSR and npm share the scope + name
const base = `https://cdn.jsdelivr.net/npm/${npmName}@${manifest.version}/dist`;

const sri = async (path: string): Promise<string> => {
  const bytes = await readFile(path);
  const digest = await crypto.subtle.digest("SHA-384", bytes.slice());
  const b64 = btoa(String.fromCharCode(...new Uint8Array(digest)));
  return `sha384-${b64}`;
};

const css = await sri("dist/ui.css");
const js = await sri("dist/ui.js");
const icons = await sri("dist/icons.svg");

const out = `// GENERATED by scripts/build-manifest.ts — do not edit by hand.
// Regenerate with \`deno task build\` (Node: \`npm run build\`, Bun: \`bun run bun:build\`).

/** The package version, as published to JSR and npm. */
export const VERSION: string = ${JSON.stringify(manifest.version)}; // x-release-please-version

/** One distributable file and where to load it from. */
export type UiAsset = {
  /** File name under dist/. */
  readonly file: string;
  /** Pinned jsDelivr URL for this exact version. */
  readonly url: string;
  /** Subresource-integrity hash of the file (sha384). */
  readonly integrity: string;
};

/** Versioned CDN base for the compiled bundle (jsDelivr, from npm). */
export const CDN_BASE: string = ${JSON.stringify(base)}; // x-release-please-version

export const UI_CSS: UiAsset = {
  file: "ui.css",
  url: ${JSON.stringify(`${base}/ui.css`)}, // x-release-please-version
  integrity: ${JSON.stringify(css)},
};

export const UI_JS: UiAsset = {
  file: "ui.js",
  url: ${JSON.stringify(`${base}/ui.js`)}, // x-release-please-version
  integrity: ${JSON.stringify(js)},
};

/** The icon set as an SVG sprite (\`<use href="…/icons.svg#icon-<name>">\`, same-origin only). */
export const UI_ICONS: UiAsset = {
  file: "icons.svg",
  url: ${JSON.stringify(`${base}/icons.svg`)}, // x-release-please-version
  integrity: ${JSON.stringify(icons)},
};

/** Every distributable, in load order. */
export const UI_ASSETS: readonly UiAsset[] = [UI_CSS, UI_JS, UI_ICONS];
`;

await writeTextFile("version.ts", out);
console.log(`Built version.ts (v${manifest.version}, ${base})`);
